---
label: IDX Config
hide_body: true
fields:
- name: ihomefinder_client_id
  type: number
  label: Ihomefinder Client ID
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: enable_idx
  type: boolean
  label: Enable IDX
pages:
- data/idx.yaml
